crudexample/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('todoapp.urls'))
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path
from todoapp import views

urlpatterns = [
    path('todo', views.todo, name='todo'),
    path('show', views.show, name='show'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.destroy, name='destroy'),
]

todoapp/models.py
from django.db import models


class Todoapp(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=15)
    is_complete = models.BooleanField(default=False)

    class Meta:
        db_table = "tasks"

    def done(self):
        if self.is_complete is True:
            return 'Task is complete'
        return 'Task is incomplete'

todoapp/forms.py
from django import forms
from todoapp.models import Todoapp


class TodoForm(forms.ModelForm):
    class Meta:
        model = Todoapp
        fields = "__all__"

todoapp/views.py
from django.shortcuts import render, redirect
from todoapp.forms import TodoForm
from todoapp.models import Todoapp


def todo(request):
    if request.method == "POST":
        form = TodoForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('show')
            except:
                pass
    else:
        form = TodoForm()
    return render(request, 'index.html', {'form': form})


def show(request):
    tasks = Todoapp.objects.all()
    return render(request, "show.html", {'tasks': tasks})


def edit(request, id):
    task = Todoapp.objects.get(id=id)
    return render(request, 'edit.html', {'task': task})


def update(request, id):
    task = Todoapp.objects.get(id=id)
    form = TodoForm(request.POST, instance=task)
    if form.is_valid():
        form.save()
        return redirect("show")
    return render(request, 'edit.html', {'task': task})


def destroy(request, id):
    task = Todoapp.objects.get(id=id)
    task.delete()
    return redirect("show")

todoapp/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
        <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
<form method="POST" class="post-form" action="/app/update/{{task.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Task id:</label>
    <div class="col-sm-4">
        <input type="text" name="id" id="id_id" required maxlength="100" value="{{ task.id }}" />
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Task Title:</label>
    <div class="col-sm-4">
        <input type="text" name="title" id="id_title" required maxlength="100" value="{{ task.title }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Task Description:</label>
    <div class="col-sm-4">
        <input type="text" name="description" id="id_description" required maxlength="254" value="{{ task.description }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Task status:</label>
    <div class="col-sm-4">
        <input type="radio" id="id_is_complete_True" name="is_complete" value="True">
            <label for="True">Complete</label><br>
        <input type="radio" id="id_is_complete_false" name="is_complete" value="False">
            <label for="False">Incomplete</label><br>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

todoapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
        <link rel="stylesheet" href="/static/css/style.css">

     </head>
<body>
<form method="POST" class="post-form" action="">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>

  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Task Title:</label>
    <div class="col-sm-4">
      {{ form.title }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Task Description:</label>
    <div class="col-sm-4">
      {{ form.description }}
    </div>
&nbsp
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

todoapp/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo Records</title>
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Task ID</th>
        <th>Task Title</th>
        <th>Task description</th>
        <th>Task completion status</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for task in tasks %}
    <tr>
        <td>{{ task.id }}</td>
        <td>{{ task.title }}</td>
        <td>{{ task.description }}</td>
        <td>{{ task.is_complete }}</td>
        <td>
            <a href="edit/{{ task.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="delete/{{ task.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="todo" class="btn btn-primary">Add New Record</a></center>
</body>
</html>